
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/viktor/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.2.0 - arm64
...
